// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtocolMsg.proto

package org.codeme.im.imcommon.model.vo;

public final class GoogleProtocolMsg {
  private GoogleProtocolMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtocolMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:googleprotocol.ProtocolMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 cmdType = 1;</code>
     * @return Whether the cmdType field is set.
     */
    boolean hasCmdType();
    /**
     * <code>required int32 cmdType = 1;</code>
     * @return The cmdType.
     */
    int getCmdType();

    /**
     * <code>required int64 senderId = 2;</code>
     * @return Whether the senderId field is set.
     */
    boolean hasSenderId();
    /**
     * <code>required int64 senderId = 2;</code>
     * @return The senderId.
     */
    long getSenderId();

    /**
     * <code>required int64 receiverId = 3;</code>
     * @return Whether the receiverId field is set.
     */
    boolean hasReceiverId();
    /**
     * <code>required int64 receiverId = 3;</code>
     * @return The receiverId.
     */
    long getReceiverId();

    /**
     * <code>required int64 chatroomId = 4;</code>
     * @return Whether the chatroomId field is set.
     */
    boolean hasChatroomId();
    /**
     * <code>required int64 chatroomId = 4;</code>
     * @return The chatroomId.
     */
    long getChatroomId();

    /**
     * <code>required int32 protocolVersion = 5;</code>
     * @return Whether the protocolVersion field is set.
     */
    boolean hasProtocolVersion();
    /**
     * <code>required int32 protocolVersion = 5;</code>
     * @return The protocolVersion.
     */
    int getProtocolVersion();

    /**
     * <code>required int32 contentLength = 6;</code>
     * @return Whether the contentLength field is set.
     */
    boolean hasContentLength();
    /**
     * <code>required int32 contentLength = 6;</code>
     * @return The contentLength.
     */
    int getContentLength();

    /**
     * <code>required string msgContent = 7;</code>
     * @return Whether the msgContent field is set.
     */
    boolean hasMsgContent();
    /**
     * <code>required string msgContent = 7;</code>
     * @return The msgContent.
     */
    java.lang.String getMsgContent();
    /**
     * <code>required string msgContent = 7;</code>
     * @return The bytes for msgContent.
     */
    com.google.protobuf.ByteString
        getMsgContentBytes();
  }
  /**
   * Protobuf type {@code googleprotocol.ProtocolMsg}
   */
  public  static final class ProtocolMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:googleprotocol.ProtocolMsg)
      ProtocolMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtocolMsg.newBuilder() to construct.
    private ProtocolMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtocolMsg() {
      msgContent_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtocolMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtocolMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              cmdType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              senderId_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              receiverId_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              chatroomId_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              protocolVersion_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              contentLength_ = input.readInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              msgContent_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.internal_static_googleprotocol_ProtocolMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.internal_static_googleprotocol_ProtocolMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg.class, org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg.Builder.class);
    }

    private int bitField0_;
    public static final int CMDTYPE_FIELD_NUMBER = 1;
    private int cmdType_;
    /**
     * <code>required int32 cmdType = 1;</code>
     * @return Whether the cmdType field is set.
     */
    public boolean hasCmdType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 cmdType = 1;</code>
     * @return The cmdType.
     */
    public int getCmdType() {
      return cmdType_;
    }

    public static final int SENDERID_FIELD_NUMBER = 2;
    private long senderId_;
    /**
     * <code>required int64 senderId = 2;</code>
     * @return Whether the senderId field is set.
     */
    public boolean hasSenderId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int64 senderId = 2;</code>
     * @return The senderId.
     */
    public long getSenderId() {
      return senderId_;
    }

    public static final int RECEIVERID_FIELD_NUMBER = 3;
    private long receiverId_;
    /**
     * <code>required int64 receiverId = 3;</code>
     * @return Whether the receiverId field is set.
     */
    public boolean hasReceiverId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required int64 receiverId = 3;</code>
     * @return The receiverId.
     */
    public long getReceiverId() {
      return receiverId_;
    }

    public static final int CHATROOMID_FIELD_NUMBER = 4;
    private long chatroomId_;
    /**
     * <code>required int64 chatroomId = 4;</code>
     * @return Whether the chatroomId field is set.
     */
    public boolean hasChatroomId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int64 chatroomId = 4;</code>
     * @return The chatroomId.
     */
    public long getChatroomId() {
      return chatroomId_;
    }

    public static final int PROTOCOLVERSION_FIELD_NUMBER = 5;
    private int protocolVersion_;
    /**
     * <code>required int32 protocolVersion = 5;</code>
     * @return Whether the protocolVersion field is set.
     */
    public boolean hasProtocolVersion() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int32 protocolVersion = 5;</code>
     * @return The protocolVersion.
     */
    public int getProtocolVersion() {
      return protocolVersion_;
    }

    public static final int CONTENTLENGTH_FIELD_NUMBER = 6;
    private int contentLength_;
    /**
     * <code>required int32 contentLength = 6;</code>
     * @return Whether the contentLength field is set.
     */
    public boolean hasContentLength() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required int32 contentLength = 6;</code>
     * @return The contentLength.
     */
    public int getContentLength() {
      return contentLength_;
    }

    public static final int MSGCONTENT_FIELD_NUMBER = 7;
    private volatile java.lang.Object msgContent_;
    /**
     * <code>required string msgContent = 7;</code>
     * @return Whether the msgContent field is set.
     */
    public boolean hasMsgContent() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required string msgContent = 7;</code>
     * @return The msgContent.
     */
    public java.lang.String getMsgContent() {
      java.lang.Object ref = msgContent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgContent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msgContent = 7;</code>
     * @return The bytes for msgContent.
     */
    public com.google.protobuf.ByteString
        getMsgContentBytes() {
      java.lang.Object ref = msgContent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCmdType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSenderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceiverId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChatroomId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProtocolVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContentLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, cmdType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, senderId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, receiverId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt64(4, chatroomId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, protocolVersion_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, contentLength_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, msgContent_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmdType_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, senderId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, receiverId_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, chatroomId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, protocolVersion_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, contentLength_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, msgContent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg)) {
        return super.equals(obj);
      }
      org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg other = (org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg) obj;

      if (hasCmdType() != other.hasCmdType()) return false;
      if (hasCmdType()) {
        if (getCmdType()
            != other.getCmdType()) return false;
      }
      if (hasSenderId() != other.hasSenderId()) return false;
      if (hasSenderId()) {
        if (getSenderId()
            != other.getSenderId()) return false;
      }
      if (hasReceiverId() != other.hasReceiverId()) return false;
      if (hasReceiverId()) {
        if (getReceiverId()
            != other.getReceiverId()) return false;
      }
      if (hasChatroomId() != other.hasChatroomId()) return false;
      if (hasChatroomId()) {
        if (getChatroomId()
            != other.getChatroomId()) return false;
      }
      if (hasProtocolVersion() != other.hasProtocolVersion()) return false;
      if (hasProtocolVersion()) {
        if (getProtocolVersion()
            != other.getProtocolVersion()) return false;
      }
      if (hasContentLength() != other.hasContentLength()) return false;
      if (hasContentLength()) {
        if (getContentLength()
            != other.getContentLength()) return false;
      }
      if (hasMsgContent() != other.hasMsgContent()) return false;
      if (hasMsgContent()) {
        if (!getMsgContent()
            .equals(other.getMsgContent())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCmdType()) {
        hash = (37 * hash) + CMDTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getCmdType();
      }
      if (hasSenderId()) {
        hash = (37 * hash) + SENDERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSenderId());
      }
      if (hasReceiverId()) {
        hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getReceiverId());
      }
      if (hasChatroomId()) {
        hash = (37 * hash) + CHATROOMID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getChatroomId());
      }
      if (hasProtocolVersion()) {
        hash = (37 * hash) + PROTOCOLVERSION_FIELD_NUMBER;
        hash = (53 * hash) + getProtocolVersion();
      }
      if (hasContentLength()) {
        hash = (37 * hash) + CONTENTLENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getContentLength();
      }
      if (hasMsgContent()) {
        hash = (37 * hash) + MSGCONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getMsgContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code googleprotocol.ProtocolMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:googleprotocol.ProtocolMsg)
        org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.internal_static_googleprotocol_ProtocolMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.internal_static_googleprotocol_ProtocolMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg.class, org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg.Builder.class);
      }

      // Construct using org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        cmdType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        senderId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        receiverId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        chatroomId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        protocolVersion_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        contentLength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        msgContent_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.internal_static_googleprotocol_ProtocolMsg_descriptor;
      }

      @java.lang.Override
      public org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg getDefaultInstanceForType() {
        return org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg.getDefaultInstance();
      }

      @java.lang.Override
      public org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg build() {
        org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg buildPartial() {
        org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg result = new org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cmdType_ = cmdType_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.senderId_ = senderId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.receiverId_ = receiverId_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.chatroomId_ = chatroomId_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.protocolVersion_ = protocolVersion_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.contentLength_ = contentLength_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.msgContent_ = msgContent_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg) {
          return mergeFrom((org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg other) {
        if (other == org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg.getDefaultInstance()) return this;
        if (other.hasCmdType()) {
          setCmdType(other.getCmdType());
        }
        if (other.hasSenderId()) {
          setSenderId(other.getSenderId());
        }
        if (other.hasReceiverId()) {
          setReceiverId(other.getReceiverId());
        }
        if (other.hasChatroomId()) {
          setChatroomId(other.getChatroomId());
        }
        if (other.hasProtocolVersion()) {
          setProtocolVersion(other.getProtocolVersion());
        }
        if (other.hasContentLength()) {
          setContentLength(other.getContentLength());
        }
        if (other.hasMsgContent()) {
          bitField0_ |= 0x00000040;
          msgContent_ = other.msgContent_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCmdType()) {
          return false;
        }
        if (!hasSenderId()) {
          return false;
        }
        if (!hasReceiverId()) {
          return false;
        }
        if (!hasChatroomId()) {
          return false;
        }
        if (!hasProtocolVersion()) {
          return false;
        }
        if (!hasContentLength()) {
          return false;
        }
        if (!hasMsgContent()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int cmdType_ ;
      /**
       * <code>required int32 cmdType = 1;</code>
       * @return Whether the cmdType field is set.
       */
      public boolean hasCmdType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 cmdType = 1;</code>
       * @return The cmdType.
       */
      public int getCmdType() {
        return cmdType_;
      }
      /**
       * <code>required int32 cmdType = 1;</code>
       * @param value The cmdType to set.
       * @return This builder for chaining.
       */
      public Builder setCmdType(int value) {
        bitField0_ |= 0x00000001;
        cmdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cmdType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmdType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmdType_ = 0;
        onChanged();
        return this;
      }

      private long senderId_ ;
      /**
       * <code>required int64 senderId = 2;</code>
       * @return Whether the senderId field is set.
       */
      public boolean hasSenderId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int64 senderId = 2;</code>
       * @return The senderId.
       */
      public long getSenderId() {
        return senderId_;
      }
      /**
       * <code>required int64 senderId = 2;</code>
       * @param value The senderId to set.
       * @return This builder for chaining.
       */
      public Builder setSenderId(long value) {
        bitField0_ |= 0x00000002;
        senderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 senderId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenderId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        senderId_ = 0L;
        onChanged();
        return this;
      }

      private long receiverId_ ;
      /**
       * <code>required int64 receiverId = 3;</code>
       * @return Whether the receiverId field is set.
       */
      public boolean hasReceiverId() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required int64 receiverId = 3;</code>
       * @return The receiverId.
       */
      public long getReceiverId() {
        return receiverId_;
      }
      /**
       * <code>required int64 receiverId = 3;</code>
       * @param value The receiverId to set.
       * @return This builder for chaining.
       */
      public Builder setReceiverId(long value) {
        bitField0_ |= 0x00000004;
        receiverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 receiverId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiverId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        receiverId_ = 0L;
        onChanged();
        return this;
      }

      private long chatroomId_ ;
      /**
       * <code>required int64 chatroomId = 4;</code>
       * @return Whether the chatroomId field is set.
       */
      public boolean hasChatroomId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int64 chatroomId = 4;</code>
       * @return The chatroomId.
       */
      public long getChatroomId() {
        return chatroomId_;
      }
      /**
       * <code>required int64 chatroomId = 4;</code>
       * @param value The chatroomId to set.
       * @return This builder for chaining.
       */
      public Builder setChatroomId(long value) {
        bitField0_ |= 0x00000008;
        chatroomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 chatroomId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearChatroomId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        chatroomId_ = 0L;
        onChanged();
        return this;
      }

      private int protocolVersion_ ;
      /**
       * <code>required int32 protocolVersion = 5;</code>
       * @return Whether the protocolVersion field is set.
       */
      public boolean hasProtocolVersion() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int32 protocolVersion = 5;</code>
       * @return The protocolVersion.
       */
      public int getProtocolVersion() {
        return protocolVersion_;
      }
      /**
       * <code>required int32 protocolVersion = 5;</code>
       * @param value The protocolVersion to set.
       * @return This builder for chaining.
       */
      public Builder setProtocolVersion(int value) {
        bitField0_ |= 0x00000010;
        protocolVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 protocolVersion = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearProtocolVersion() {
        bitField0_ = (bitField0_ & ~0x00000010);
        protocolVersion_ = 0;
        onChanged();
        return this;
      }

      private int contentLength_ ;
      /**
       * <code>required int32 contentLength = 6;</code>
       * @return Whether the contentLength field is set.
       */
      public boolean hasContentLength() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required int32 contentLength = 6;</code>
       * @return The contentLength.
       */
      public int getContentLength() {
        return contentLength_;
      }
      /**
       * <code>required int32 contentLength = 6;</code>
       * @param value The contentLength to set.
       * @return This builder for chaining.
       */
      public Builder setContentLength(int value) {
        bitField0_ |= 0x00000020;
        contentLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 contentLength = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearContentLength() {
        bitField0_ = (bitField0_ & ~0x00000020);
        contentLength_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msgContent_ = "";
      /**
       * <code>required string msgContent = 7;</code>
       * @return Whether the msgContent field is set.
       */
      public boolean hasMsgContent() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required string msgContent = 7;</code>
       * @return The msgContent.
       */
      public java.lang.String getMsgContent() {
        java.lang.Object ref = msgContent_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgContent_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msgContent = 7;</code>
       * @return The bytes for msgContent.
       */
      public com.google.protobuf.ByteString
          getMsgContentBytes() {
        java.lang.Object ref = msgContent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgContent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msgContent = 7;</code>
       * @param value The msgContent to set.
       * @return This builder for chaining.
       */
      public Builder setMsgContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msgContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msgContent = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgContent() {
        bitField0_ = (bitField0_ & ~0x00000040);
        msgContent_ = getDefaultInstance().getMsgContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string msgContent = 7;</code>
       * @param value The bytes for msgContent to set.
       * @return This builder for chaining.
       */
      public Builder setMsgContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msgContent_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:googleprotocol.ProtocolMsg)
    }

    // @@protoc_insertion_point(class_scope:googleprotocol.ProtocolMsg)
    private static final org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg();
    }

    public static org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProtocolMsg>
        PARSER = new com.google.protobuf.AbstractParser<ProtocolMsg>() {
      @java.lang.Override
      public ProtocolMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtocolMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtocolMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtocolMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.codeme.im.imcommon.model.vo.GoogleProtocolMsg.ProtocolMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_googleprotocol_ProtocolMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_googleprotocol_ProtocolMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ProtocolMsg.proto\022\016googleprotocol\"\234\001\n\013" +
      "ProtocolMsg\022\017\n\007cmdType\030\001 \002(\005\022\020\n\010senderId" +
      "\030\002 \002(\003\022\022\n\nreceiverId\030\003 \002(\003\022\022\n\nchatroomId" +
      "\030\004 \002(\003\022\027\n\017protocolVersion\030\005 \002(\005\022\025\n\rconte" +
      "ntLength\030\006 \002(\005\022\022\n\nmsgContent\030\007 \002(\tB4\n\037or" +
      "g.codeme.im.imcommon.model.voB\021GooglePro" +
      "tocolMsg"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_googleprotocol_ProtocolMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_googleprotocol_ProtocolMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_googleprotocol_ProtocolMsg_descriptor,
        new java.lang.String[] { "CmdType", "SenderId", "ReceiverId", "ChatroomId", "ProtocolVersion", "ContentLength", "MsgContent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
