imclient:
  api-server:
    url: http://127.0.0.1:8031
  netty:
    server:
      host: 127.0.0.1
      port: 10001
  user:
    password: 111111
    username: admin
  machineId: ${HOST_MACHINE_ID:1}
  datacenterId: ${HOST_DATACENTER_ID:1}

spring:
  main:
    #关闭web
    web-application-type: 'NONE'
  profiles:
    active: dev
