imserver:
  netty:
    server:
      port: 10001
spring:
  main:
    #关闭web
    web-application-type: 'NONE'
  profiles:
    active: dev

  redis:
    database: 5
    host: 127.0.0.1
    lettuce:
      pool:
        max-idle: 100
        max-wait: 2000
        min-idle: 50
    password: ''
    port: 6380
    timeout: 3000
