server:
  port: 10008

spring:
  application:
    name: im-forward
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
  profiles:
    active: dev
  redis:
    database: 5
    host: 127.0.0.1
    lettuce:
      pool:
        max-idle: 100
        max-wait: 2000
        min-idle: 50
    password: ''
    port: 6380
    timeout: 3000
# 打开该配置会导致无法建立netty连接
#  main:
#    #关闭web
#    web-application-type: 'NONE'

codeme:
  im:
    imforward:
      zookeeper-url: localhost:2181
      forward-id: 1
